### ISSUE TITLE
Plugin not loading mods onto server

### ISSUE THREAD

**Issue by TheAmazingTaco** [Phoenix84/TorchPrivateMods#2]
I am currently trying to load a collection through this plugin but after the update to torch yesterday, it no longer applies the mods to the server.

**Comment by Gwindalmir** [comment]
Which collection are you trying to use, and can you post the torch/server log, including the mod downloading section? You can redact sensitive information such as IP.

**Comment by TheAmazingTaco** [comment]
[https://pastebin.com/h2XFQ7JS](url) <- SpaceEngineers-Dedicated.log

**Comment by Gwindalmir** [comment]
So you are saying, despite the fact the mods download, when the session loads, the mods are not in the world?

**Comment by TheAmazingTaco** [comment]
That is correct. The mods download, the CMD window says that the mods are up to date but nothing is showing up when I log onto the server itself.

**Comment by Gwindalmir** [comment]
Ok, the issue was the mods from the collection were not being added to the checkpoint anymore. Not sure what changed.
